"""Token table

Revision ID: 18ad8c182477
Revises: 56899827a148
Create Date: 2014-01-24 15:48:50.515708

"""

# revision identifiers, used by Alembic.
revision = '18ad8c182477'
down_revision = '56899827a148'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'token',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uploadid', sa.Integer(), nullable=True, autoincrement=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['uploadid'], ['upload.id'],
                                onupdate='cascade', ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    ### end Alembic commands ###
