"""upload tickets

Revision ID: 1251e2c34cbb
Revises: 18ad8c182477
Create Date: 2014-01-24 20:16:14.508637

"""

# revision identifiers, used by Alembic.
revision = '1251e2c34cbb'
down_revision = '18ad8c182477'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('tickets', sa.Integer(),
                                      nullable=True, default=1))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'tickets')
    ### end Alembic commands ###
