"""upload created

Revision ID: 4520669b81de
Revises: 1251e2c34cbb
Create Date: 2014-01-24 23:35:02.577495

"""

# revision identifiers, used by Alembic.
revision = '4520669b81de'
down_revision = '1251e2c34cbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'created')
    ### end Alembic commands ###
